### ISSUE TITLE
Testplan for 2024-10-21

### ISSUE THREAD

**Issue by b-mayr-1984** [gruppe-adler/Shoot_and_Scoot.Tanoa#44]
This issue is about finding and fixing bugs after feature freeze for the next game night (scheduled for 2024-10-21).

### [ Streamer features](https://docs.google.com/presentation/d/1BGDOxqqZw4T6js3oQ4mPr4E7f8NLZsPS85MUAAIYvco/edit#slide=id.g27941e9ac27_1_9) 
- [x] fix for `Destroyed` marker in MP scenario
- [ ] ~for Streamator slots~
- [x] for ACE spectator slots
- [x] DF bearing lines (see https://feedback.bistudio.com/T175116) 

### EW
- CrowsEW 2.2.1 vs. 2.0.0
  - [x] omni-jammer
  - [x] spectrum device jammer
  - [x] TFAR radio tracking
  - [x] ICOM device for EW operators (6d09165e59ce22ef72ca3c2f88fad2572b814b07)
- [x] DF truck without TFAR DFing (c01a98aa3fef2a3dc44ef89edad39b82d1c08ca2)

### other
- [x] D30 without LG shells (https://github.com/gruppe-adler/grad_D30_artilleryTweak/commit/61dbcc5dbeb3cc27f62e5eee59663aa13166d9c9)
- [x] mortar workaround (8b06f13456c4abeb1a822cfbc330ba64199e54cb)
- [x] drone workaround (1ed3f52c0cb5694e52b90253cfe5ce3eb9ae6673)
- [x] server RPT message when players use workarounds (c01d11b4b249c53b01a6631267eaf5c1e663061a)
- [x] get ingame docu feedback from other players
- [x] stealing SR and LR radios from killed enemies
   - [x] same with enemy UAV terminals (should not work)
- [x] Darter laser designator on map

## Fix
- [x] `Cruise Missile HE` marker not deleted after splash (see https://github.com/gruppe-adler/Shoot_and_Scoot.Tanoa/issues/44#issuecomment-2322918957)
- [x] VLS sensor display not showing laser spot (see https://github.com/gruppe-adler/Shoot_and_Scoot.Tanoa/issues/44#issuecomment-2322921647)
- [ ] ~video live feed only visible to shooter (see https://github.com/gruppe-adler/Shoot_and_Scoot.Tanoa/issues/44#issuecomment-2322925693)~
  - I see no way how to fix this 
- [x] ICOM device causing script errors in RPT log (see https://github.com/gruppe-adler/Shoot_and_Scoot.Tanoa/issues/44#issuecomment-2322932348)
- [x] `Destroyed` marker visible to ordinary players (see https://github.com/gruppe-adler/Shoot_and_Scoot.Tanoa/issues/44#issuecomment-2322924986)
- [x] remove NLAW from Blufor MRAP and LSV

**Comment by b-mayr-1984** [comment]
After the cruise missile hits, the tracking map marker (for streamers only) is not deleted but remains on the impact site.
![image](https://github.com/user-attachments/assets/77c48e97-54df-49fa-b9af-1d258f91836d)

Found while testing with @nomisum and Boholt.

**Comment by b-mayr-1984** [comment]
When a player is remote controlling the VLS system, 
![](https://static.wikia.nocookie.net/armedassault/images/e/e9/Arma3-ship-liberty-01.jpg/revision/latest?cb=20190622095334)
the red laser spot marker will only then appear on the sensor display,
![sensor_display_laser_target_selected](https://github.com/user-attachments/assets/3766dead-d869-47a5-8087-10d1c5d46021)
if the laser designator was already turned on when the player decided to step into the VLS launcher (via UAVterminal).

If the designator is turned on while already controling the VLS launcher (via UAVterminal), then it will not show.

Turning the laser designator **off** is properly synched between clients though.

This is probably a BI bug.

Found while testing with @nomisum and Boholt.

**Comment by b-mayr-1984** [comment]
> ### [ Streamer features](https://docs.google.com/presentation/d/1BGDOxqqZw4T6js3oQ4mPr4E7f8NLZsPS85MUAAIYvco/edit#slide=id.g27941e9ac27_1_9)
> * [x]  fix for `Destroyed` marker in MP scenario

The marker is visible to normal players. 
![image](https://github.com/user-attachments/assets/f218800a-d34d-41ff-a3cd-f4a0df4fd2a6)
Intended behaviour is that only streamers and Zeus sees it, though.


Found while testing with @nomisum and Boholt.

**Comment by b-mayr-1984** [comment]
Cruise missile video live feed is only visible to the person firing the VLS.
![cruise_missile_mid_flight](https://github.com/user-attachments/assets/7fc34c68-cf42-45e3-8eb3-2732160d21a6)
Intended behaviour is that both CMD and 2iC see the live feed, though.


Found while testing with @nomisum and Boholt.

**Comment by b-mayr-1984** [comment]
> ### EW
> * CrowsEW 2.2.1 vs. 2.0.0
>   [..]
>   * [x]  ICOM device for EW operators ([6d09165](https://github.com/gruppe-adler/Shoot_and_Scoot.Tanoa/commit/6d09165e59ce22ef72ca3c2f88fad2572b814b07))

Listening into enemy TFAR radio comms with the [ICOM device](https://crowdedlight.github.io/Crows-Electronic-Warfare/spectrum/tracking/tfar-tracking.html?highlight=icom#listening-in) causes script errors in 

https://github.com/michail-nikolaev/task-force-arma-3-radio/blob/ce23ed88adc71af3c0f48fdefb52261177bfb0da/addons/core/functions/fnc_activeLrRadio.sqf#L44

and subsequently in

https://github.com/gruppe-adler/Shoot_and_Scoot.Tanoa/blob/4c7e5a7187c199d216228832329803c5c79543e8/scripts/tfar-persistence/functions/fn_transferRadiosAcrossRespawn.sqf#L48


```sqf
12:30:24 Error in expression <lse {
TFAR_OverrideActiveLRRadio
};
};

TF_lr_active_radio
>
12:30:24   Error position: <TF_lr_active_radio
>
12:30:24   Error Undefined variable in expression: tf_lr_active_radio
12:30:24 File z\tfar\addons\core\functions\fnc_activeLrRadio.sqf..., line 44



12:30:24 Error in expression <veLr = call TFAR_fnc_activeLRRadio;
if (_activeLr isEqualTo _radio) exitWith {
p>
12:30:24   Error position: <_activeLr isEqualTo _radio) exitWith {
p>
12:30:24   Error Undefined variable in expression: _activelr
12:30:24 File mpmissions\__CUR_MP.tanoa\scripts\tfar-persistence\functions\fn_transferRadiosAcrossRespawn.sqf..., line 48
```
### blame TFAR
It appears quite obvious that this is a TFAR bug.
- The LR function, mentioned in the RPT log, does not provide a defined default value for the returned variable.
- The SR function does though. https://github.com/michail-nikolaev/task-force-arma-3-radio/blob/ce23ed88adc71af3c0f48fdefb52261177bfb0da/addons/core/functions/fnc_activeSwRadio.sqf#L21

Found while testing with @nomisum.


### problem not visible to players
Other then the script errors being logged, we couldn't find any other problems.
So as long as players don't set their game to bring all script errors to the surface, they should be fine.


@Crowdedlight I think you should know of this. Sooner or later someone might report this for [CrowsEW](https://github.com/Crowdedlight/Crows-Electronic-Warfare).

**Comment by Crowdedlight** [comment]
@b-mayr-1984 What did the discussion with Joko end up with? Saw the issue on TFAR was closed. 

I believe I am calling TFAR in unscheduled as it is called from a 
```
["MouseButtonDown", {_this call FUNC(spectrumDeviceMouseDown)}] call CBA_fnc_addDisplayHandler;
```

So wondering if it is something I can fix on my end? I don't recall having seen this error before when testing through.

**Comment by b-mayr-1984** [comment]
> @b-mayr-1984 What did the discussion with Joko end up with? Saw the issue on TFAR was closed.

@Crowdedlight he explained to me how he could be certain that the problem is related to the environment.

TFAR does not support `scheduled` calls to its functions. 
The error messages in the RPT log however are proof that they are called from `unscheduled` environment.

> I believe I am calling TFAR in unscheduled as it is called from a
> 
> ```
> ["MouseButtonDown", {_this call FUNC(spectrumDeviceMouseDown)}] call CBA_fnc_addDisplayHandler;
> ```
> 
> So wondering if it is something I can fix on my end? I don't recall having seen this error before when testing through.

It could very well be that Gruppe Adler code, that is reacting to the TFAR frequency changes (which are triggered by listening in via ICOM device from CrowsEW), causes the `scheduled` calls to TFAR functions. I need to investigate further.

**Comment by Crowdedlight** [comment]
Fair enough. About to leave for vacation but just give me a ping here if you figure out it is something on my end. Can have a look at it when I get home again.

**Comment by b-mayr-1984** [comment]
@jokoho48 you seem to be absolutely right with your assessment of the problem I mentioned in https://github.com/gruppe-adler/Shoot_and_Scoot.Tanoa/issues/44#issuecomment-2322932348.

I did some test where I 
- removed [ gruppe_adler_mod](https://github.com/gruppe-adler/gruppe_adler_mod) from the modest
- wrapped my Shoot and Scoot code that call TFAR functions in [CBA_fnc_directCall](https://cbateam.github.io/CBA_A3/docs/files/common/fnc_directCall-sqf.html)

There are no more script errors then. 
Thanks for taking the time to educate a SQF noob/hater here. 😅  




@Crowdedlight there seems to be nothing to do here on CrowsEW side. Problems seem to be all in Gruppe Adler code.

**Comment by b-mayr-1984** [comment]
Unfortunately the Cruise Missile featured needed to be removed entirely (see 77896c13ee549153f4cafdf86696510c48fed658).
![](https://camo.githubusercontent.com/ce74e82860b4767d8c5205a04ff882f00057ce7bd02f6f73b5540a2022105f24/68747470733a2f2f7374617469632e77696b69612e6e6f636f6f6b69652e6e65742f61726d656461737361756c742f696d616765732f652f65392f41726d61332d736869702d6c6962657274792d30312e6a70672f7265766973696f6e2f6c61746573743f63623d3230313930363232303935333334) 

The reason is that the Vanilla feature appears to be to unreliable on dedicated servers. 🙁 
(see also [discussion on ACE3 discord](https://discord.com/channels/976165959041679380/976224730422063214/1281723473571483669))

I don't see a way how I could fix this.

**Comment by b-mayr-1984** [comment]
> Unfortunately the Cruise Missile featured needed to be removed entirely (see [77896c1](https://github.com/gruppe-adler/Shoot_and_Scoot.Tanoa/commit/77896c13ee549153f4cafdf86696510c48fed658)). 
> 
> The reason is that the Vanilla feature appears to be to unreliable on dedicated servers. 🙁 
> (see also [discussion on ACE3 discord](https://discord.com/channels/976165959041679380/976224730422063214/1281723473571483669))
> 
> I don't see a way how I could fix this.

I assume the problem is related to this issue.
- https://feedback.bistudio.com/T182587 

More discussion at:
- https://discord.com/channels/105462288051380224/108187245529268224/1258016111342125058 
- https://discord.com/channels/105462288051380224/108187245529268224/1258034763428659242

**Comment by b-mayr-1984** [comment]
> ## Test
> ### Streamer features
> * [ ]  for Streamator slots

This will not work. :-(

Streamator slots need to be `VirtualSpectator_F`. 
- But those can't be Zeuses. 
- Streamer features are mostly tied to being Zeus though.

**Comment by b-mayr-1984** [comment]
I call it done. 

The additional Cruise Missile features will only work for the gunner of the VLS though.
Everything else (like streamer features) I couldn't get to work.
