### ISSUE TITLE
Tweak supply stations / targets

### ISSUE THREAD

**Issue by b-mayr-1984** [gruppe-adler/Shoot_and_Scoot.Tanoa#7]
Test players had several issues with these supply stations / targets.
(see [custom compositions](https://github.com/gruppe-adler/Shoot_and_Scoot.Tanoa/tree/main/compositions))
![BLUFOR supply station](https://user-images.githubusercontent.com/76476468/192612370-bb771c9d-ea17-4bd1-9e36-c685145355be.jpg)
![OPFOR supply station](https://user-images.githubusercontent.com/76476468/192612373-1062e18e-3a0b-4455-9fde-8e6ae3b6fc4f.jpg)

### Complaints
- during first round they were to tanky 
  - nerfing them to spawn with only 50% health led to good player feedback 
- 3x different containers confused multiple players
  - it wasn't clear when a target has been destroyed
- Camo nets only work on very flat ground without immediate self-destruction

### Todos

- [x] remove both repair and fuel container and just keep the ammo container as a single target
- [x] implement the stations to spawn with 50% health
- [x] remove camo nets altogether if this physics issue can not be fixed
